# Config file for automatic testing at travis-ci.org
sudo: false

language: python
python: 3.5

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox coverage codecov
  - coverage erase

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}

after_success:
    - coverage combine
    # Report coverage results to codecov.io
    - codecov

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: SalemHarrache
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: alexandriagroup/rakuten-ws
    condition: $TOXENV == py27
